# Generated by Django 4.2 on 2023-10-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='es_usuario',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
