# Generated by Django 4.2 on 2023-11-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_nota_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='es_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='es_usuario',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=75),
        ),
    ]
